version: 2
jobs:
  install:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
  deploy:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - attach_workspace:
          at: ~/
      - run: npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - require-approval:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: v2.0.0
      - deploy:
          requires:
            - require-approval
          filters:
            branches:
              only: v2.0.0