version: 2
jobs:
  install:
    docker:
      - image: 'circleci/node:8'
    steps:
      - checkout
      - run:
          name: lint
          command: npm run lint
      - run:
          name: npm_install
          command: npm install
  deploy:
    working_directory: ./
    docker:
      - image: 'circleci/node:8'
    steps:
      - run: npm run semantic-release || true

workflows:
  version: 2
  test_and_realease:
    jobs:
      - install
      - deploy:
          requieres:
            - install