on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "Tiene conflictos"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
